<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="10034" started-at="2015-12-16T11:31:52Z" finished-at="2015-12-16T11:32:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10034" started-at="2015-12-16T11:31:52Z" finished-at="2015-12-16T11:32:02Z">
      <class name="tests.solTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:tests.solTest@5474c6c]" name="beforeTest" is-config="true" duration-ms="0" started-at="2015-12-16T13:31:52Z" finished-at="2015-12-16T13:31:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="f()[pri:0, instance:tests.solTest@5474c6c]" name="f" duration-ms="10016" started-at="2015-12-16T13:31:52Z" finished-at="2015-12-16T13:32:02Z">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method org.testng.internal.TestNGMethod.f() didn't finish within the time-out 10000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.f() didn't finish within the time-out 10000
	at lockFreeQueue.Queue.enqueue(Queue.java:75)
	at tests.solTest.f(solTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:tests.solTest@5474c6c]" name="afterTest" is-config="true" duration-ms="0" started-at="2015-12-16T13:32:02Z" finished-at="2015-12-16T13:32:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- tests.solTest -->
    </test> <!-- Default test -->
  </suite> <!-- Suite -->
</testng-results>
